Rename mods.toml to neoforge.mods.toml
neoforged/FancyModLoader pull request #100
Opened 2024-03-20 06:57 UTC by Matyrobbrt

This is targeted for a new major (in 1.20.5).  
By renaming the file, we can improve error reporting in case Forge mods are found, and not attempt to load them. 3rd party tools can also use the presence or absence of this file to determine the loader of the mod.

2024-03-20 17:33 UTC, marchermans requested changes

2024-03-20 18:35 UTC, Technici4n commented on loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
`neoforge` is the name of the project, not `neo`.

2024-03-21 16:02 UTC, esotericist commented on loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
just a bit down from the above message link we have https://discord.com/channels/313125603924639766/1154167065519861831/1219932597296168960

`neoforge.mods.toml` seems obviously more correct to me, and it is implied to be the preferred option according to maintainer discussion

2024-03-21 17:40 UTC, marchermans commented on loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
Even if it is NeoForge.mods.toml. it still needs to be in the meta inf directory

2024-03-21 20:22 UTC, 0xilly commented on loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
I would rather us not jam through something not voted on it would be trivial to do another maintainer vote.

2024-03-21 20:43 UTC, Technici4n commented on loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
I think that the opinion is clear enough. Voting should be a last resort option anyway.

2024-03-22 03:15 UTC, 0xilly commented
We either follow the vote or we don’t the “small enough to ignore” excuse doesn’t cut it IMHO

Anita Anderson

> On Mar 21, 2024, at 4:44 PM, Technici4n ***@***.***> wrote:
>
> @Technici4n commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java](https://github.com/neoforged/FancyModLoader/pull/100#discussion_r1534655101):
>
>> @@ -29,7 +29,7 @@
>  public abstract class AbstractModProvider implements IModProvider
>  {
>      private static final   Logger LOGGER    = LogUtils.getLogger();
> -    protected static final String MODS_TOML = "META-INF/mods.toml";
>
> I think that the opinion is clear enough. Voting should be a last resort option anyway.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/neoforged/FancyModLoader/pull/100#discussion_r1534655101), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAKFA4RXVLEPZ3UG4SPVD7DYZNBB3AVCNFSM6AAAAABE64VQB2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJTGM4DEOJXGE).
> You are receiving this because you commented.Message ID: ***@***.***>

2024-03-22 05:24 UTC, Technici4n commented
The vote decided between 1) root folder or META-INF and 2) whether to rename the file or not. So we rename the file and keep it in META-INF. Orion wasn't happy because maty forgot to keep the file in META-INF (now this is fixed). Other than that, there's no objection that I'm aware of.

2024-03-25 08:29 UTC, marchermans approved these changes

2024-03-25 19:16 UTC, Technici4n approved these changes

2024-03-25 19:17 UTC, merged