Add STARTUP configs for early config loading/usage
neoforged/FancyModLoader pull request #150
Opened 2024-05-27 20:41 UTC by TelepathicGrunt

I think this is all that is needed. JUnit tests ran so I didn't completely kill the build lol

closes https://github.com/neoforged/NeoForge/issues/723

2024-05-28 19:15 UTC, Technici4n commented
I'm happy to test this once there is a corresponding NF PR. :wink:

2024-05-28 19:21 UTC, TelepathicGrunt commented
@Technici4n what needs to happen on the Neo PR? Just a test mod there to test it? How would I have the Neo pr build against this fml pr?

2024-05-28 19:28 UTC, Technici4n commented
You can use PR publishing for that. 😉

Check https://github.com/neoforged/FancyModLoader/pull/150#issuecomment-2134028746 once it's finished publishing.

2024-06-02 07:49 UTC, Technici4n submitted a review, later dismissed

2024-06-02 08:31 UTC, Matyrobbrt requested changes

2024-06-02 08:31 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/config/ConfigTracker.java
> +    public void openConfig(final ModConfig config, final Path configBasePath, @Nullable Path configOverrideBasePath) {
You should either mark this as internal, or the entire class.

2024-06-02 08:31 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/config/ModConfig.java
> +         * Suffix is "-startup" by default.
```suggestion
         * Startup configs are for configurations that need to run as early as possible.
         * Loaded as soon as the config is registered to FML.
         * Please be aware when using them, as using these configs to enable/disable registration and anything that must be present on both sides
         * can cause clients to have issues connecting to servers with different config values.
         * Stored in the global config directory.
         * Not synced.
         * Suffix is "-startup" by default.
```

2024-06-02 11:54 UTC, Matyrobbrt approved these changes

2024-06-02 12:50 UTC, merged