Replace use of "extension" with explicit method on RuntimeDistCleaner
neoforged/FancyModLoader pull request #155
Opened 2024-06-02 20:46 UTC by shartte

This removes the need for unchecked casts in `getExtension()`.

2024-06-02 22:13 UTC, XFactHD requested changes

2024-06-02 22:13 UTC, XFactHD commented on loader/src/main/java/net/neoforged/fml/common/asm/RuntimeDistCleaner.java
> +    public static void setDistribution(Dist dist) {
This method should either be non-static or be called statically instead of on an instance of this class

2024-06-02 22:21 UTC, XFactHD approved these changes

2024-06-03 09:46 UTC, marchermans commented
I understand that this breaks binary compat, but in my eyes we can merge this. What do you guys think?

2024-06-03 16:33 UTC, merged