Use ByteBuddy in unit tests to avoid having to add add-opens to unit tests
neoforged/FancyModLoader pull request #171
Opened 2024-06-24 16:41 UTC by shartte

What it says on the tin :-)

We use the ByteBuddy agent implicitly already through Mockito.

2024-06-24 16:45 UTC, Matyrobbrt requested changes

2024-06-24 16:45 UTC, Matyrobbrt commented on loader/src/test/java/net/neoforged/fml/loading/LauncherTest.java
> +        // We abuse the ByteBuddy agent that Mockito also uses to open java.lang to UnionFS
You can move this into a beforeall

2024-06-24 18:33 UTC, Matyrobbrt approved these changes

2024-06-24 18:33 UTC, merged

2024-07-01 10:02 UTC, SquidDev commented
Apologies if you're already aware, but there's plans to disable dynamic loading of agents (and so `ByteBuddyAgent.install`) in the future — see [JEP 451](https://openjdk.org/jeps/451). This definitely doesn't matter right now, as NeoForged is pinned to Java 21, but worth bearing in mind for the future!