Allow specifying a debug context for the early window
neoforged/FancyModLoader pull request #197
Opened 2024-08-24 16:51 UTC by IMS212

Pretty self explanatory.

2024-08-24 16:53 UTC, embeddedt commented
What is the default value of `GLFW_CONTEXT_DEBUG`?

2024-08-24 16:54 UTC, IMS212 commented
False.

2024-08-26 10:27 UTC, marchermans requested changes

2024-08-26 10:27 UTC, marchermans commented on loader/src/main/java/net/neoforged/fml/loading/FMLConfig.java
> +        EARLY_WINDOW_DEBUG("earlyWindowDebug", Boolean.FALSE, "Early window uses debug context"),
This should be commented as: `Early window initializes GLFW Window with a debugable OpenGL Context, allowing for better debugging of OpenGL calls`

2024-10-25 18:26 UTC, closed without merging