Add Java Core Mods
neoforged/FancyModLoader pull request #79
Opened 2024-01-21 23:33 UTC by shartte

Mods must ship a separate Jar-file (for example via jar-in-jar) and mark it as FMLModType: LIBRARY to make it load above the GAME layer. They then must provide an implementation of ICoreMod via the Java ServiceLoader to contribute their transformers.

This tries to avoid loading the script-engine based coremod library unless any modfile contains such coremod scripts.

2024-01-22 08:36 UTC, Technici4n commented
We do not have generics for `ITransformer` yet. :P

2024-01-22 15:37 UTC, Technici4n commented
Ah, yes we do. Didn't read why the build was failing. 😁

Good idea in any case. We can change the interface later but for now this is good enough. I also expect noticeable startup time improvements once we move the NF coremods to this.

2024-05-05 20:32 UTC, Matyrobbrt requested changes

2024-05-05 20:32 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/loading/CoreModScriptLoader.java
> +        public boolean equals(Object obj) {
Err... this is a record already?

2024-05-05 20:32 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/loading/FMLServiceProvider.java
> +        var pluginLayer = Launcher.INSTANCE.findLayerManager()
You should be able to use the new methods in FML to load services.

2024-06-02 08:57 UTC, Matyrobbrt requested changes

2024-06-02 08:57 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/loading/FMLServiceProvider.java
> +            return Collections.emptyList();
```suggestion
            return List.of();
```

2024-06-02 08:57 UTC, Matyrobbrt commented on loader/src/main/java/net/neoforged/fml/loading/ModSorter.java
> +            return LoadingModList.of(plugins, ms.systemMods, ms.systemMods.stream().map(mf -> (ModInfo) mf.getModInfos().get(0)).collect(toList()), e.getIssues(), Map.of());
While you're at it, the loading mod list issues aren't concatenated here.

2024-06-02 08:57 UTC, Matyrobbrt commented on loader/src/test/java/net/neoforged/fml/loading/ModFileBuilder.java
> +    public ModFileBuilder addService(String interfaceClass, String implementationClass) throws IOException {
Add an overload with a class parameter.

2024-06-02 09:55 UTC, Matyrobbrt approved these changes

2024-06-02 09:58 UTC, merged