Add headers to crash report extenders
neoforged/FancyModLoader pull request #88
Opened 2024-02-10 22:11 UTC by Matyrobbrt

Neo already has a hook to add a crash report header, but the method contents are empty. This PR allows crash report extenders to add headers to crash reports.  

Connector can, for instance, use this to show a warning at the top of the report telling users to not report the crash to mod authors.

2024-02-10 22:23 UTC, Su5eD approved these changes

2024-02-11 13:38 UTC, sciwhiz12 requested changes

2024-02-11 13:38 UTC, sciwhiz12 commented on loader/src/main/java/net/neoforged/fml/ISystemReportExtender.java
> +    default String getHeader() {
This is unused here. I assume there'll be a future NeoForge PR to implement usages of this?

Also, why is this nullable?

2024-02-11 13:38 UTC, sciwhiz12 commented on loader/src/main/java/net/neoforged/fml/ISystemReportExtender.java
> +     * {@return the label of the crash report value to add}
This isn't for the crash report but the _system_ report, as evidenced by the name of the class. 

While crash reports have a system report, a system report can be generated independently of a crash report -- see `PerfCommand` (`/perf`) where it saves a system report alongside the performance metrics report.

2024-02-11 13:38 UTC, sciwhiz12 commented on loader/src/main/java/net/neoforged/fml/ISystemReportExtender.java
> +    @Nullable
Why is this and `get()` both nullable?

2024-02-11 17:21 UTC, Technici4n commented on loader/src/main/java/net/neoforged/fml/CrashReportCallables.java
> +    public static void registerHeader(Supplier<String> header) {
custom functional interface?

2024-02-11 17:21 UTC, Technici4n commented on loader/src/main/java/net/neoforged/fml/ICrashReportHeader.java
> +    String getHeader();
should it be nullable in case there is no header to be added?

2024-02-11 17:25 UTC, Technici4n approved these changes

2024-02-11 17:28 UTC, sciwhiz12 approved these changes

2024-02-12 16:16 UTC, merged