Add `registerConfig` method to `ModContainer`
neoforged/FancyModLoader pull request #99
Opened 2024-03-20 02:05 UTC by dhyces

Adds a method to `ModContainer` to create and add a mod config from a given type and spec. This is added to simplify the current verbose `addConfig` method. I understand that the config system is currently being looked at for a future refactor and as such recognize that the lifetime of this method may be short.

2024-03-20 02:09 UTC, Shadows-of-Fire approved these changes

2024-03-20 04:27 UTC, ChampionAsh5357 commented
I would also add the method to change the filename of the config and redirect the `ModLoadingContext` methods to use these new methods within the container.

2024-03-20 23:37 UTC, dhyces commented
> I would also add the method to change the filename of the config and redirect the `ModLoadingContext` methods to use these new methods within the container.

Yeah, I don't see why not. Aside from that, should anything be done with the validation currently in the `ModLoadingContext` methods? Could move it into `addConfig`, unless there is a case to register an empty mod config, or can change it to only log a warning without early return.

2024-03-21 02:37 UTC, ChampionAsh5357 commented
> Yeah, I don't see why not. Aside from that, should anything be done with the validation currently in the `ModLoadingContext` methods? Could move it into `addConfig`, unless there is a case to register an empty mod config, or can change it to only log a warning without early return.

Since `#addConfig` didn't have the validation in the first place, I would leave it alone. However, they can be moved to the two methods you created.

2024-03-24 17:01 UTC, Technici4n requested changes
Could you please move the `isEmpty` check to the new methods as well, and deprecate the old methods for removal?

2024-03-24 18:32 UTC, Technici4n approved these changes

2024-03-25 08:51 UTC, merged